Repository nuxeo/nuxeo-web-ui, pull requests merged in 2024-02, with the labels that each got.

#2178 WEBUI-1453: elements ftests not working in cross repo check - node18
  .github/workflows/cross-repo.yaml
  .github/workflows/ftest.yaml
Labels: 3.1.x

#2179 WEBUI-1314: sauce labs compatibility with firefox geckoDriver
  .github/workflows/test.yaml
  karma.conf.js
Labels: 3.1.x

#2180 WEBUI-1314: Backward Port: sauce labs compatibility with firefox geckoDriver
  .github/workflows/test.yaml
  karma.conf.js
Labels: 3.0.x

#2182 WEBUI-1455: Analysis on retention cicd ftest failure
  packages/nuxeo-web-ui-ftest/wdio.conf.js
Labels: 3.1.x

#2188 WEBUI-1457: Nuxeo build failing Building addons failing in CI pipeline
  package.json
Labels: 3.1.x

#2189 WEBUI-1457: Backward Port: Nuxeo build failing Building addons failing in CI pipeline
  package.json
Labels: 3.0.x

#2183 WEBUI-1455: analysis on retention cicd ftest failure lts 2023
  packages/nuxeo-web-ui-ftest/features/step_definitions/admin.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/audit.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/browser.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/bulk_edit.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/clipboard.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/cloud.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/collections.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/comments.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/compare.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/create_dialog.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/csv-import.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/doc_suggestion.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/document.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/favorites.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/group.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/history.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/home.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/import_dialog.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/login.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/permissions.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/personal.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/picture.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/preview.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/recents.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/search.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/spreadsheet.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/support/fixtures/comments.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/support/fixtures/consumers.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/support/fixtures/documents.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/support/fixtures/groups.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/support/fixtures/localstorage.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/support/fixtures/oauth2.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/support/fixtures/providers.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/support/fixtures/searches.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/support/fixtures/users.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/support/fixtures/vocabularies.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/support/fixtures/workflows.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/support/screenshots.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/support/ui_config.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/tasks.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/trash.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/ui.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/upload.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/user.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/user_settings.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/versions.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/video.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/vocabularies.js
Labels: 3.1.x

#2193 WEBUI-1446: CSP headers without the insecure unsafe-inline directive
  plugin/web-ui/addon/src/main/resources/OSGI-INF/web-ui-properties.xml
  plugin/web-ui/addon/src/main/resources/web/nuxeo.war/ui/config.jsp
  plugin/web-ui/addon/src/main/resources/web/nuxeo.war/ui/index.jsp
Labels: testing

#2190 WEBUI-1455: Backward Port: Analysis on retention cicd ftest failure
  package.json
  packages/nuxeo-web-ui-ftest/features/step_definitions/admin.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/audit.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/browser.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/bulk_edit.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/clipboard.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/cloud.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/collections.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/comments.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/compare.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/create_dialog.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/csv-import.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/doc_suggestion.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/document.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/favorites.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/group.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/history.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/home.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/import_dialog.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/login.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/permissions.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/personal.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/picture.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/preview.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/recents.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/search.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/spreadsheet.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/support/fixtures/comments.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/support/fixtures/consumers.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/support/fixtures/documents.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/support/fixtures/groups.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/support/fixtures/localstorage.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/support/fixtures/oauth2.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/support/fixtures/providers.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/support/fixtures/searches.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/support/fixtures/users.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/support/fixtures/vocabularies.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/support/fixtures/workflows.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/support/screenshots.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/support/ui_config.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/tasks.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/trash.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/ui.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/upload.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/user.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/user_settings.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/versions.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/video.js
  packages/nuxeo-web-ui-ftest/features/step_definitions/vocabularies.js
  packages/nuxeo-web-ui-ftest/package.json
  packages/nuxeo-web-ui-ftest/wdio.conf.js
Labels: 3.0.x
