Repository nuxeo/nuxeo-web-ui, pull requests merged in 2025-01, with the labels that each got.

#2418 WEBUI 597 Fix alignment & style defects in nuxeo-picture-formats and nuxeo-video-conversions lts 2021
  elements/document/nuxeo-picture-formats.js
Labels: 3.0.x

#2417 WEBUI-597: Fix alignment & style defects in nuxeo-picture-formats and nuxeo-video-conversions lts 2023
  elements/document/nuxeo-picture-formats.js
Labels: 3.1.x

#2415 WebUI-785: nuxeo document tree icon needs to be focusable lts 2021
  elements/nuxeo-document-tree/nuxeo-document-tree.js
Labels: 3.0.x

#2414 WEBUI-785: nuxeo-document-tree icon needs to be focusable lts 2023
  elements/nuxeo-document-tree/nuxeo-document-tree.js
Labels: 3.1.x

#2433 WEBUI-1634: Upgrade upload artifact version from v3 to v4
  .github/workflows/catalog.yaml
  .github/workflows/cross-repo.yaml
  .github/workflows/ftest.yaml
  .github/workflows/main.yaml
Labels: 3.0.x

#2432 WEBUI-1634: Upgrade upload artifact version from v3 to v4
  .github/workflows/catalog.yaml
  .github/workflows/cross-repo.yaml
  .github/workflows/ftest.yaml
  .github/workflows/main.yaml
  .github/workflows/veracode-3.0.x.yaml
  .github/workflows/veracode-3.1.x.yaml
  .github/workflows/veracode-lts-2025.yaml
Labels: lts-2025

#2437 WEBUI-1634: Upgrade download artifact version from v3 to v4
  .github/workflows/veracode-3.0.x.yaml
  .github/workflows/veracode-3.1.x.yaml
Labels: 3.1.x

#2439 WEBUI-1634: Upgrade download artifact version from v3 to v4
  .github/workflows/ftest.yaml
Labels: 3.1.x

#2446 WEBUI-1634: Upgrade download artifact version from v3 to v4
  .github/workflows/ftest.yaml
Labels: 3.1.x

#2440 WEBUI-1634: Backward Port: Upgrade download artifact version from v3 to v4
  .github/workflows/ftest.yaml
Labels: 3.0.x
